### PR TITLE
Ajn54

### PR DESCRIPTION
**Pull request by ebeshero**
Pull request to merge Aaron's updates to the website into the master branch.

### CODE REVIEW

**Comment by dotfig** [comment]
How would I resolve these conflicts?

**Comment by ebeshero** [comment]
@ajnewton1 I think I've just resolved the conflict. It was over the changes you'd made to the menu.html. I've just resolved it so YOUR version replaces what's on the master branch!

**Comment by ebeshero** [comment]
I'm going to just merge this pull request in...everyone okay with that?

**Comment by ebeshero** [comment]
@ajnewton1 At some point when we can meet and look at two computers, I'll show you how to resolve a conflict like this. It's not hard, but it involves carefully comparing files and making sure which is the version that you want to keep.

**Pull request merged**
